### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by renebohne**
If I add the lib via npm (instead of yarn), the tslib dependency was missing. 
This results in this error: Error: Cannot find module 'tslib'.

### CODE REVIEW

**Comment by renebohne** [comment]
btw: this happened when I upgraded from 1.3.1 to 1.5.0

**Comment by JulianWowra** [comment]
Thank you for your pull request 👏
I have reworked the dependencies and it should be working now.

---

If you still have problems with the new version, please feel free to create an issue!

**Comment by renebohne** [comment]
I tested 1.5.1 and now the dependencies work with npm.
I selected the lower version number for tslib based on your yarn.lock. But I am happy that you added newer versions.
